# Generated by Django 5.1.4 on 2025-01-14 08:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beacons',
            fields=[
                ('id', models.BigAutoField(default=uuid.UUID('a3217f38-88f0-4733-b0cb-cc61bfb4657e'), editable=False, primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
                ('signal_strength', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.BigAutoField(default=uuid.UUID('e8fa9e95-c8a7-4bbf-9250-59c0229786d9'), editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('image', 'image'), ('video', 'video'), ('text', 'text')], default='text', max_length=10)),
                ('beacon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.beacons')),
            ],
        ),
    ]
