# Generated by Django 5.1.4 on 2025-02-21 13:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('advertisement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField()),
                ('start_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='advertisements/')),
                ('type', models.CharField(choices=[('image', 'image'), ('video', 'video'), ('text', 'text')], default='text', max_length=10)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('beacon_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('minor', models.IntegerField(blank=True, null=True)),
                ('major', models.IntegerField(blank=True, null=True)),
                ('location_name', models.CharField(db_index=True, max_length=100)),
                ('signal_strength', models.FloatField(blank=True, null=True)),
                ('battery_status', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='campaign.advertisement')),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='campaign.beacon')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='beacon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='campaign.beacon'),
        ),
        migrations.CreateModel(
            name='BeaconMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('image', 'image'), ('video', 'video'), ('text', 'text')], default='text', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(null=True)),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='campaign.beacon')),
            ],
        ),
    ]
