# Generated by Django 5.1.4 on 2025-03-03 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='beacon',
        ),
        migrations.CreateModel(
            name='AdvertisementAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='campaign.advertisement')),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beacon', to='campaign.beacon')),
            ],
            options={
                'unique_together': {('beacon', 'advertisement')},
            },
        ),
    ]
