# Generated by Django 5.1.4 on 2025-02-17 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='major',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='beacon',
            name='minor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
