# Generated by Django 5.1.4 on 2025-01-14 08:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisements',
            name='id',
        ),
        migrations.RemoveField(
            model_name='beacons',
            name='id',
        ),
        migrations.AddField(
            model_name='advertisements',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2bf40d72-3d15-4206-976b-327d608f4f65'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='beacons',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('12db9d14-0cb4-4ee4-a820-f64462129ef6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
