# Generated by Django 5.1.4 on 2025-01-28 03:01

from uuid import uuid4
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='advertisement_id',
            field=models.UUIDField(db_column='advertisement_id', default=uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beacons',
            name='battery_status',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='beacons',
            name='beacon_id',
            field=models.UUIDField(db_column='beacon_id', default=uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
