# Generated by Django 5.1.4 on 2025-03-04 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_remove_advertisement_beacon_advertisementassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementassignment',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_assignments', to='campaign.advertisement'),
        ),
        migrations.AlterField(
            model_name='advertisementassignment',
            name='beacon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_assignments', to='campaign.beacon'),
        ),
    ]
