# Generated by Django 5.1.4 on 2025-03-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_alter_advertisementassignment_advertisement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beacon',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
