# Generated by Django 5.1.4 on 2025-02-01 02:01

from uuid import uuid4
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_alter_advertisements_advertisement_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacons',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='advertisement_id',
            field=models.UUIDField(db_column='advertisement_id', default=uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beacons',
            name='battery_status',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beacons',
            name='signal_strength',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
