# Generated by Django 5.1.4 on 2025-03-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_beacon_latitude_beacon_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='major',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='minor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
