# Generated by Django 5.1.4 on 2025-03-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_alter_beacon_latitude_alter_beacon_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='latitude',
            field=models.FloatField(blank=True, default=9.145, null=True),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='longitude',
            field=models.FloatField(blank=True, default=38.7525, null=True),
        ),
    ]
