# Generated by Django 5.1.4 on 2025-04-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_adsaved_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adlike',
            name='liked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adsaved',
            name='saved',
            field=models.BooleanField(default=True),
        ),
    ]
