# Generated by Django 5.1.4 on 2025-05-23 09:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisements', '0001_initial'),
        ('beacons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementAssignment',
            fields=[
                ('assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_assignments', to='advertisements.advertisement')),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_assignments', to='beacons.beacon')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('beacon', 'advertisement')},
            },
        ),
    ]
