# Generated by Django 5.1.7 on 2025-03-24 11:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('advertisement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='advertisements/')),
                ('type', models.CharField(choices=[('image', 'image'), ('video', 'video'), ('text', 'text')], default='text', max_length=10)),
            ],
        ),
    ]
