# Generated by Django 5.1.7 on 2025-04-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_alter_savedad_unique_together_remove_savedad_ad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsaved',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
