# Generated by Django 5.1.4 on 2025-05-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_alter_adlike_liked_alter_adsaved_saved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='media_file',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='type',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='url',
        ),
    ]
