# Generated by Django 5.1.7 on 2025-03-15 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisements', '0001_initial'),
        ('beacons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='advertisements.advertisement')),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='beacons.beacon')),
            ],
        ),
    ]
